arsenal:
  - Arsenal
  - Gunners
chelsea:
  - Chelsea
liverpool:
  - Liverpool
man_city:
  - Manchester City
real_madrid:
  - Real Madrid
barcelona:
  - Barcelona
premier_league:
  - Premier League
champions_league:
  - Champions League
