# .github/workflows/ci.yml (excerpt)
- uses: actions/setup-python@v5
  with: { python-version: "3.12" }
- run: python -m pip install --upgrade pip
- run: pip install -r requirements.txt -r requirements-dev.txt
